# Generated by Django 4.2.5 on 2024-02-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0050_rename_brand_name_contact_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
