# Generated by Django 4.2.5 on 2024-02-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0051_address_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
